# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [5]:
b = np.arange(10,50,1)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [6]:
b.shape

(40,)

5. Print the type of the previous array in question 3

In [7]:
type(b)

numpy.ndarray

6. Print the numpy version and the configuration


In [8]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Syed Saad Hasan Emad/.conda/envs/programs\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Syed Saad Hasan Emad/.conda/envs/programs\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Syed Saad Hasan Emad/.conda/envs/programs\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Syed Saad Hasan Emad/.conda/envs/programs\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Syed Saad Hasan Emad/.conda/envs/programs\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Syed Saad Hasan Emad/.conda/envs/programs\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Syed Saad Hasan Emad/.conda/envs/programs\\Library\\l

7. Print the dimension of the array in question 3


In [9]:
print(b.ndim)

1


8. Create a boolean array with all the True values

In [13]:
c = np.ones((10), dtype=bool)
c

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [17]:
d = np.arange(0,10,1).reshape(2,5)
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. Create a three dimensional array



In [19]:
e = np.arange(0,9,1).reshape(3,3)
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [20]:
b = b[::-1]
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [23]:
f = np.zeros(10,dtype=int)
f[4] = 1

f

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [25]:
g = np.identity(3,dtype=int)
g

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [26]:
arr = np.array([1, 2, 3, 4, 5],dtype=float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [32]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])


arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [33]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr3 = (arr1 == arr2)
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [34]:
arr = np.array([1, 2, 3, 4, 5])
odd = arr[arr%2==1]
odd

array([1, 3, 5])

18. Replace all odd numbers to -1 from previous array

In [35]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr%2==1] = -1
arr

array([-1,  2, -1,  4, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [36]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [37]:
x = np.ones((5,5),dtype=int)

x[1:-1,1:-1] = 0
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [38]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [39]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:,:] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [40]:
array2d = np.random.randint(10, size=(4,3))
array2d[:1,:]

array([[1, 9, 6]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [42]:
array2d = np.random.randint(10, size=(4,3))
array2d[1:2,1:2]

array([[6]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [43]:
array2d = np.random.randint(10, size=(4,3))
array2d[:2,2:3]

array([[5],
       [3]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [44]:
h = np.random.randn(10,10)
print(np.max(h),np.min(h))

2.4930351374092794 -3.098994242476529


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [45]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [46]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!='Will']


array([[-1.20721703,  0.43187238,  0.30224483,  0.23859112],
       [-0.45715346, -3.10101228,  0.6785424 ,  0.53996609],
       [-1.45676078,  1.08932876, -0.64344671,  1.27123738],
       [ 0.35573381,  1.99623843,  0.68513035, -0.63641626],
       [ 0.88010844,  0.47642443,  2.07898153, -0.25491405]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [50]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[(names!='Will') & (names!='Joe')]

array([[-0.53419981, -2.67771074, -0.4981716 ,  0.11149444],
       [-1.03254104,  0.40419897,  0.22168554,  1.17178218]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [51]:
i = np.random.randint(1,15, size=(5,3))
i

array([[ 8, 14,  7],
       [ 9, 14, 14],
       [ 3,  8, 14],
       [14,  2,  1],
       [13, 13,  7]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [52]:
j = np.random.randint(1,16, size=(2,2,4))
j

array([[[12,  8,  2,  9],
        [11, 12,  1,  2]],

       [[12, 12, 12, 12],
        [10,  5,  2, 13]]])

33. Swap axes of the array you created in Question 32

In [55]:
np.transpose(j)

array([[[12, 12],
        [11, 10]],

       [[ 8, 12],
        [12,  5]],

       [[ 2, 12],
        [ 1,  2]],

       [[ 9, 12],
        [ 2, 13]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [64]:
k = np.random.randint(10,size=(10,))
k = np.sqrt(k)
k[k<0.5] = 0
k

array([1.        , 0.        , 0.        , 0.        , 2.        ,
       2.44948974, 1.        , 0.        , 1.73205081, 2.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [66]:
l = np.random.randn(12)
m = np.random.randn(12)
np.maximum(l,m)

array([ 1.28473264,  1.9103286 ,  0.66195236,  0.96259605, -0.45618944,
        2.43225856,  1.10998549,  0.59001135, -0.74231968,  2.19005549,
        2.10046744,  1.14292065])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [67]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [68]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
n = np.setdiff1d(a, b)
n

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [69]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray=np.delete(sampleArray, 1, 1)
np.insert(sampleArray, 1,newColumn , axis=1)

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [70]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [71]:
a=np.random.randn(20)
np.sum(a)

-0.7037095198379442