# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.reshape(a, (2, -1))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [5]:
a = np.arange(0,10).reshape((2,5))
b = np.ones(10,dtype=int).reshape((2,5))
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
a = np.arange(0,10).reshape((2,5))
b = np.ones(10,dtype=int).reshape((2,5))
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [6]:
a = np.arange(0,10).reshape((2,5))
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [7]:
a = np.arange(0,15).reshape((3,5))
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [8]:
a = np.arange(0,15)
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [11]:
a = np.random.randn(5,5)
np.square(a)

array([[4.39783148e-03, 8.68173075e-01, 1.00052042e+00, 1.34496604e-01,
        3.60019628e+00],
       [1.72422651e-01, 2.62478001e-01, 4.67750390e+00, 1.43389130e-02,
        3.93753728e-01],
       [3.34359244e+00, 1.91524075e-01, 1.82127592e+00, 3.24486090e-01,
        5.47769104e-01],
       [1.66181987e+00, 7.73837573e-03, 1.89341339e+00, 4.88017071e-04,
        1.08545210e-01],
       [6.00517232e-01, 6.29341539e-02, 7.59984543e-01, 2.69111886e+00,
        7.35384854e-01]])

## Question:8

### Create 5x6 an array and find the mean?

In [13]:
b = np.random.randn(5,6)

np.mean(b)

0.2050491936163084

## Question:9

### Find the standard deviation of the previous array in Q8?

In [14]:

np.std(b)

1.0064213311262982

## Question:10

### Find the median of the previous array in Q8?

In [15]:

np.median(b)

0.20099030093311934

## Question:11

### Find the transpose of the previous array in Q8?

In [16]:

b.T

array([[ 0.27108929,  1.05032506, -1.51964756, -0.87462925,  1.67779298],
       [ 0.05994637, -0.74596961, -0.56823246, -1.48692754,  1.3032054 ],
       [-0.08776454,  1.62198694, -0.24014461,  0.4246536 ,  0.03130431],
       [ 0.73416934,  0.27086924,  1.13267526,  1.58183272,  1.51067486],
       [ 0.83171258, -0.99207813, -0.32113328,  2.3028536 ,  0.40319776],
       [ 0.29416345,  0.13111136, -0.38802751, -0.82449888, -1.43303494]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [17]:
c = np.arange(0,16).reshape((4,4))
np.trace(c)


30

## Question:13

### Find the determinant of the previous array in Q12?

In [18]:
np.linalg.det(c)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [19]:

print(np.percentile(c, 5),np.percentile(c, 95))

0.75 14.25


## Question:15

### How to find if a given array has any null values?

In [20]:
d = np.empty((3,3))


d[:] = np.NaN
np.isnan(d)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])